- name: variables
  hosts: local
  connection: local
  # vars: #Play level variables
  #   GREET: "PLAY"
  # vars_files:
  # - course.yaml
  # vars_prompt:
  # - name: GREET
  #   prompt: Enter the value
  #   private: false
  tasks:
  - name: print the variable
    # vars:
    #   GREET: "TASK"
    ansible.builtin.debug:
      msg: "Hello from {{ GREET }}"

#1. preference is for command line or args
#2. Task level
#3. files level
#4. prompt level
#5. play level
#6. inventory level
#7. roles (laterwe wil discuss)
