- name: install packages
  hosts: web
  become: yes
  task:
  - name: install packages
    ansible.builtin.package:
      name: "{{ item }}"
      state: installed
    loop:
    - git
    - gcc
    - zip
    - mysql