- name: filters
  hosts: local
  connection: local
  tasks: 
  - name: handle undefine variable
    ansible.builtin.debug:
      msg: " Hello {{ person | default('suresh') }}"
  - name: converting string to list
    vars:
      fruits: "apples,banana,orange" #string
    ansible.builtin.debug:
      msg: "Fruits are: {{ fruits | split(',') }}"


  - name: convert map into list
    vars:
      course:
        name: ansible
        duration: 120hrs
        trainer: sivakumar
    ansible.builtin.debug:
      msg: "course info: {{ course | dict2items }}"

  - name: convert list into map
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '120hrs'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "course info: {{ course | items2dict }}"

  - name: convert lower to upper
    vars:
      name: "Algot Sarika"
    ansible.builtin.debug:
      msg: "Hello {{name | upper}}"